services:
  - type: web
    name: order-management-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: SEED_DATA_ENABLED
        value: "true"
      - key: INITIAL_ADMIN_EMAIL
        value: harireddyhari123@gmail.com
      - key: INITIAL_ADMIN_PASSWORD
        value: Admin@123
      - key: STRIPE_CURRENCY
        value: inr
